services:
  search-service:
    build: .
    container_name: search-service
    ports:
      - "8080:8080"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped
